name: Integração contínua

on:
  push:
    branches: 
      ['master']

jobs: 
  integracao-continua:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Usando o Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.
      - name: install e build 
        run: |
          npm install
          npm run deploy
